export default {
  login: "sadavoya",
  id: 198468,
  node_id: "MDQ6VXNlcjE5ODQ2OA==",
  avatar_url: "https://avatars0.githubusercontent.com/u/198468?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sadavoya",
  html_url: "https://github.com/sadavoya",
  followers_url: "https://api.github.com/users/sadavoya/followers",
  following_url: "https://api.github.com/users/sadavoya/following{/other_user}",
  gists_url: "https://api.github.com/users/sadavoya/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sadavoya/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sadavoya/subscriptions",
  organizations_url: "https://api.github.com/users/sadavoya/orgs",
  repos_url: "https://api.github.com/users/sadavoya/repos",
  events_url: "https://api.github.com/users/sadavoya/events{/privacy}",
  received_events_url: "https://api.github.com/users/sadavoya/received_events",
  type: "User",
  site_admin: false,
  name: "A Sadavoy",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 14,
  public_gists: 3,
  followers: 5,
  following: 2,
  created_at: "2010-02-06T16:53:00Z",
  updated_at: "2020-10-15T18:45:51Z",
};
