export default [
  {
    login: "CodeSkool",
    id: 4909220,
    node_id: "MDQ6VXNlcjQ5MDkyMjA=",
    avatar_url: "https://avatars2.githubusercontent.com/u/4909220?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/CodeSkool",
    html_url: "https://github.com/CodeSkool",
    followers_url: "https://api.github.com/users/CodeSkool/followers",
    following_url:
      "https://api.github.com/users/CodeSkool/following{/other_user}",
    gists_url: "https://api.github.com/users/CodeSkool/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/CodeSkool/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/CodeSkool/subscriptions",
    organizations_url: "https://api.github.com/users/CodeSkool/orgs",
    repos_url: "https://api.github.com/users/CodeSkool/repos",
    events_url: "https://api.github.com/users/CodeSkool/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/CodeSkool/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "KevinHock",
    id: 3076393,
    node_id: "MDQ6VXNlcjMwNzYzOTM=",
    avatar_url: "https://avatars1.githubusercontent.com/u/3076393?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/KevinHock",
    html_url: "https://github.com/KevinHock",
    followers_url: "https://api.github.com/users/KevinHock/followers",
    following_url:
      "https://api.github.com/users/KevinHock/following{/other_user}",
    gists_url: "https://api.github.com/users/KevinHock/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/KevinHock/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/KevinHock/subscriptions",
    organizations_url: "https://api.github.com/users/KevinHock/orgs",
    repos_url: "https://api.github.com/users/KevinHock/repos",
    events_url: "https://api.github.com/users/KevinHock/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/KevinHock/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "JulesStoltz",
    id: 44175898,
    node_id: "MDQ6VXNlcjQ0MTc1ODk4",
    avatar_url: "https://avatars0.githubusercontent.com/u/44175898?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JulesStoltz",
    html_url: "https://github.com/JulesStoltz",
    followers_url: "https://api.github.com/users/JulesStoltz/followers",
    following_url:
      "https://api.github.com/users/JulesStoltz/following{/other_user}",
    gists_url: "https://api.github.com/users/JulesStoltz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/JulesStoltz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/JulesStoltz/subscriptions",
    organizations_url: "https://api.github.com/users/JulesStoltz/orgs",
    repos_url: "https://api.github.com/users/JulesStoltz/repos",
    events_url: "https://api.github.com/users/JulesStoltz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/JulesStoltz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Dmitriy-Vas",
    id: 48634525,
    node_id: "MDQ6VXNlcjQ4NjM0NTI1",
    avatar_url: "https://avatars2.githubusercontent.com/u/48634525?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Dmitriy-Vas",
    html_url: "https://github.com/Dmitriy-Vas",
    followers_url: "https://api.github.com/users/Dmitriy-Vas/followers",
    following_url:
      "https://api.github.com/users/Dmitriy-Vas/following{/other_user}",
    gists_url: "https://api.github.com/users/Dmitriy-Vas/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Dmitriy-Vas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Dmitriy-Vas/subscriptions",
    organizations_url: "https://api.github.com/users/Dmitriy-Vas/orgs",
    repos_url: "https://api.github.com/users/Dmitriy-Vas/repos",
    events_url: "https://api.github.com/users/Dmitriy-Vas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Dmitriy-Vas/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AylorKat",
    id: 27773355,
    node_id: "MDQ6VXNlcjI3NzczMzU1",
    avatar_url: "https://avatars1.githubusercontent.com/u/27773355?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AylorKat",
    html_url: "https://github.com/AylorKat",
    followers_url: "https://api.github.com/users/AylorKat/followers",
    following_url:
      "https://api.github.com/users/AylorKat/following{/other_user}",
    gists_url: "https://api.github.com/users/AylorKat/gists{/gist_id}",
    starred_url: "https://api.github.com/users/AylorKat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/AylorKat/subscriptions",
    organizations_url: "https://api.github.com/users/AylorKat/orgs",
    repos_url: "https://api.github.com/users/AylorKat/repos",
    events_url: "https://api.github.com/users/AylorKat/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AylorKat/received_events",
    type: "User",
    site_admin: false,
  },
];
